import type { Metadata } from 'next'
import { Geist, Geist_Mono, BBH_Sans_Bartle } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})
const bbhbartel = BBH_Sans_Bartle({
  variable: '--font-bbhbartet',
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'CineHive',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bbhbartel.variable} antialiased`}
      >
        {/* <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange> */}
        {children}
        {/* </ThemeProvider> */}
      </body>
    </html>
  )
}
