import type { Metadata } from 'next'
import { Geist, Geist_Mono, BBH_Sans_Bartle } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import OpeningAnimation from '@/components/OpeningAnimation'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})
const bbhbartel = BBH_Sans_Bartle({
  variable: '--font-bbhbartet',
  subsets: ['latin'],
  weight: ['400'],
  fallback: ['Roboto'],
})

const sdAsian = localFont({
  src: '../public/fonts/sdasian.woff2',
  variable: '--font-sdasian',
})

export const metadata: Metadata = {
  title: 'CineHive',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${sdAsian.className} ${geistSans.variable} ${geistMono.variable} ${bbhbartel.variable} ${sdAsian.className} antialiased font-sans`}
      >
        <OpeningAnimation />
        {/* <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange> */}
        <main className="font-sans">{children}</main>
        {/* </ThemeProvider> */}
      </body>
    </html>
  )
}
